config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "site#index"

  resources :artists, only: [:new, :create, :destroy, :index]
  resources :fans, only: [:new, :create, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :artist
  belongs_to :album
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_one :user, :as => :user_role, dependent: :destroy
  has_many :transactions
  has_many :albums
  accepts_nested_attributes_for :user
end

app/models/fan.rb
class Fan < ActiveRecord::Base
  has_one :user, as: :user_role, dependent: :destroy
  has_many :payment_methods
  has_many :transactions
  accepts_nested_attributes_for :user

  # TODO
  # Add subclasses for Credit Card, PayPal, Amazon, etc
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  belongs_to :fan
  has_many :transactions
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
  has_many :playlists, through: :playlist_songs
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :fan
  belongs_to :artist
  belongs_to :payment_method
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :user_role, polymorphic: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def new
    @artist = Artist.new
    @user = @artist.build_user
  end

  def create
  end

  def destroy
  end

  def index
    @artists = Artist.all
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image, user_attributes: [ :id, :email, :password ])
  end
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
  def new
    @fan = Fan.new
    @user = @fan.build_user
  end

  #Cant figure out how to create the fan with nested user attributes

  def create
    binding.pry
    @fan = Fan.new(fan_params)
    if @fan.save
      message = "Fan Created Successfully!"
      redirect_to artists_path, notice: message
    else
      flash.alert = "Your fan profile could not be created. Please correct the errors below."
      render :new
    end
  end

  def destroy
  end

  private

  #temporary whitelist all for troubleshooting
  def fan_params
    params.require(:fan).permit!
  end

end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<h1>Albums#index</h1>
<p>Find me in app/views/albums/index.html.erb</p>

app/views/albums/index.html.haml
<h1>Albums#index</h1>
<p>Find me in app/views/albums/index.html.erb</p>

app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

app/views/albums/new.html.haml
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/index.html.haml
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/new.html.haml
.row
  .col-xs-2
  .col-xs-8
    .new-artist-container
      %p.new-artist-header New Artist
      = simple_form_for @artist, :html => {:multipart => true} do |f|
        = f.file_field :image, label: "Upload Artist Image"
        .name-header Name
        = f.text_field :name, label: 'Name'
        = f.simple_fields_for @user do |u|
          .email-header Email
          = u.text_field :email, label: 'Email'
          .password-header Password
          = u.password_field :password, label: 'Password'
        = f.submit 'Submit', class: 'btn btn-success'
  .col-xs-2

app/views/fans/new.html.erb
<h1>Fans#new</h1>
<p>Find me in app/views/fans/new.html.erb</p>

app/views/fans/new.html.haml
.row
  .col-xs-2
  .col-xs-8
    .new-fan-container
      %p.new-fan-header New Fan
      = simple_form_for @fan do |f|
        .name-header Name
        = f.text_field :name, label: 'Name'
        = f.simple_fields_for @user do |u|
          .email-header Email
          = u.text_field :email, label: 'Email'
          .password-header Password
          = u.password_field :password, label: 'Password'
        = f.submit 'Submit', class: 'btn btn-success'
  .col-xs-2

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Donote
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"}/
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Josefin+Slab|Satisfy|Ubuntu+Condensed", :rel => "stylesheet", :type => "text/css"}/
  %body
    - if notice
      %p.notice= notice
    - if alert
      %p.alert= alert
    %nav.navbar.navbar-default
      .container-fluid
        .nav-container
          .home-logo= link_to "Donote",root_path
          - if user_signed_in?
            = link_to content_tag(:i,nil, class: 'fa fa-sign-out right-nav-link pull-right'), destroy_user_session_path, method: :delete
            = link_to content_tag(:i,nil, class: 'fa fa-user right-nav-link pull-right'), edit_user_registration_path
          - else
            = link_to content_tag(:i,nil, class: 'fa fa-sign-in right-nav-link pull-right'), new_user_session_path
    .container-fluid
      = yield

app/views/payment_methods/new.html.erb
<h1>PaymentMethods#new</h1>
<p>Find me in app/views/payment_methods/new.html.erb</p>

app/views/payment_methods/new.html.haml
<h1>PaymentMethods#new</h1>
<p>Find me in app/views/payment_methods/new.html.erb</p>

app/views/site/index.html.erb
<h1>Welcome to Donote.io</h1>

app/views/site/index.html.haml
.row
  .col-xs-12
    .fan-container
      = link_to image_tag('', :class => "img-responsive fan-img"), new_fan_path
      %p.fan-text Fan
.row
  .col-xs-12
    .artist-container
      = link_to image_tag('', :class => "img-responsive artist-img"), new_artist_path
      %p.artist-text Artist

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/new.html.haml
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/transactions/new.html.erb
<h1>Transactions#new</h1>
<p>Find me in app/views/transactions/new.html.erb</p>

app/views/transactions/new.html.haml
<h1>Transactions#new</h1>
<p>Find me in app/views/transactions/new.html.erb</p>